[tool.poetry]
name = "ruyi"
version = "0.1.0"
description = "Package manager for RuyiSDK"
keywords = ["ruyi", "ruyisdk"]
# license = { file = "LICENSE-Apache.txt" }
license = "Apache-2.0"
readme = "README.md"
authors = [
  # { name = "WANG Xuerui", email = "wangxuerui@iscas.ac.cn" }
  "WANG Xuerui <wangxuerui@iscas.ac.cn>",
]

#requires-python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ['py311']


[tool.poetry.dependencies]
python = ">=3.11"

pyxdg = "^0.28"
rich = "^13.5"

# build
nuitka = "^1.8"
