name: Dist build

on: [push, pull_request]

jobs:
  dist:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ruyisdk/ruyi-python-dist:20240121
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - .:/home/b/ruyi:ro
        - /tmp/build:/build
        - /tmp/poetry-cache:/poetry-cache
        - /tmp/ccache:/ccache

    strategy:
      matrix:
        arch:
          - amd64
          # TODO: arm64 & riscv64

    steps:
      - uses: actions/checkout@v4

      - name: Cache deps and Nuitka output
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-tgt-${{ matrix.arch }}-lock-${{ hashFiles('poetry.lock') }}
          path: |
            /ccache
            /poetry-cache

      - name: Run dist
        run: /home/b/ruyi/scripts/dist-inner.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruyi.${{ matrix.arch }}
          path: /build/ruyi
          compression-level: 0  # the Nuitka onefile payload is already compressed
