name: Lint

on:
  push:
    paths:
      - pyproject.toml
      - '**.py'
  pull_request:
    paths:
      - pyproject.toml
      - '**.py'

jobs:
  lint:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  pylic:
    name: license compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: poetry
      - name: Run check
        run: scripts/check-license.sh
